#pragma once

#include <cstdint>

#include "features/feature_list.h"

// Example robot actions that could be implemented using this interface:
//    move to approach
//    move to start position
//    start welding
//    start weaving
//    move weld
//    stop welding
//    stop weaving
//
// Request/response flow for robot actions:
//
//    START request: feature [+ Data]                 // Request to start an action for the specified feature, with optional action-specific data
//        -> FeatureNotSupported                      // Feature not supported by robot interface
//        -> DataInvalid [+ Data]                     // Data blob is invalid or malformed for the requested feature (but feature is supported), data (if any, feature specific) contains additional information
//        -> Success [+ Data]                         // Action completed immediately successfully, data (if any, feature specific) contains additional information
//        -> SuccessInProgress: action_id [+ Data]    // Action has been started successfully and is ongoing (+action_id identifies the action instance), data (if any, feature specific) contains additional information
//        -> Failure [+ Data]                         // Action either failed to start or completed immediately with failure, data (if any, feature specific) contains additional information
//
//    UPDATE request: action_id, [+ Data]             // Request to update an ongoing action identified by action_id, with optional action-specific data (used to modify parameters, read status, stop early, etc. depending on feature)
//        -> NotInProgress                            // No such action in progress (= unknown action_id)
//        -> DataInvalid [+ Data]                     // Data blob is invalid or malformed for the requested action (but action is in progress), data (if any, feature specific) contains additional information
//        -> Success [+ Data]                         // Action handled the update request successfully, data (if any, feature specific) contains additional information
//        -> Failure [+ Data]                         // Action failed to handle the update request, data (if any, feature specific) contains additional information
//
//    STATUS message: feature, [+ Data]               // Message sent by any feature on robot interface asynchronously to report robot status, errors, etc., data (if any, feature specific) contains additional information
//    FINISHED message: action_id, success, [+ Data]  // Message sent by after a long-running action has finished (successfully or with failure), data (if any, feature specific) contains additional information
//                                                    // action_id identifies the action instance that has finished, success indicates whether the action completed successfully or with failure
//                                                    // Only sent for actions that were started with a START request and did not complete immediately (i.e., after a SuccessInProgress response)
//
// Note: data blobs are feature-specific and their structure/format is defined by the feature implementation, see features documentation for details.
// Note: action_id is generated by the robot interface when an action is started and is used to identify the action instance for updates and finished messages.

namespace aergo::module::helpers::robot_interface
{
    enum class ReqType : uint8_t
    {
        START_ACTION,    // Request to start a new action
        UPDATE_ACTION    // Request to update an ongoing action
    };

    /// @brief Structure of a robot interface request message.
    /// There are two types of requests: START_ACTION and UPDATE_ACTION.
    /// START_ACTION is used to start a new action, UPDATE_ACTION is used to update an ongoing action.
    /// START_ACTION requires the feature to be specified, while UPDATE_ACTION requires the feature and the action_id to identify the active action instance.
    /// START_ACTION: send { .req_type = ReqType::START_ACTION, .feature = <feature>, .action_id = 0 } followed by the data blob (if any).
    /// UPDATE_ACTION send: { .req_type = ReqType::UPDATE_ACTION, .feature = <feature>, .action_id = <id of action instance> }, followed by the data blob (if any).
    struct Request
    {
        ReqType req_type;       // Type of the request
        RobotFeature feature;   // Specifies which feature the request is for (used both for START_ACTION and UPDATE_ACTION)
        uint64_t action_id;     // Used to identify the action instance (used only for UPDATE_ACTION)
    };

    enum class RespType : uint8_t
    {
        FEATURE_NOT_SUPPORTED,  // Requested feature is not supported by the robot interface
        NOT_IN_PROGRESS,        // No such action in progress (unknown action_id)
        DATA_INVALID,           // Data blob is invalid or malformed for the requested feature/action
        SUCCESS_IN_PROGRESS,    // Action has been started successfully and is ongoing
        SUCCESS,                // Action request was successful (finished or updated successfully)
        FAILURE                 // Action request failed (could not be started or updated or failed)
    };

    /// @brief Structure of a robot interface response message.
    /// There are several types of responses: FEATURE_NOT_SUPPORTED, NOT_IN_PROGRESS, DATA_INVALID, SUCCESS_IN_PROGRESS, SUCCESS, and FAILURE.
    ///     FEATURE_NOT_SUPPORTED is used to indicate that the requested feature is not supported by the robot interface (for START_ACTION requests).
    ///     NOT_IN_PROGRESS is used to indicate that there is no such action in progress (unknown action_id) (for UPDATE_ACTION requests).
    ///     DATA_INVALID is used to indicate that the data blob is invalid or malformed for the requested feature/action.
    ///     SUCCESS_IN_PROGRESS is used to indicate that the action has been started successfully and is ongoing (for START_ACTION requests).
    ///     SUCCESS is used to indicate that the action request was successful (finished or updated successfully).
    ///     FAILURE is used to indicate that the action request failed (could not be started or updated or failed).
    ///
    /// Any response type except FEATURE_NOT_SUPPORTED and NOT_IN_PROGRESS may include a data blob with additional information (feature-specific).
    ///
    /// For START_ACTION requests, SUCCESS responses indicate that the action has completed immediately successfully (action_id is not used).
    /// For START_ACTION requests, SUCCESS_IN_PROGRESS responses indicate that the action has been started and is ongoing (+action_id identifies the action instance).
    /// For UPDATE_ACTION requests, SUCCESS responses indicate that the action has been updated successfully (action_id is echoed back from the request).
    struct Response
    {
        RespType resp_type;     // Type of the response
        uint64_t action_id;     // Identifies the action instance (new id for START_ACTION on SUCCESS_IN_PROGRESS, copied from request for UPDATE_ACTION)
    };
    
    /// @brief Structure of a robot interface status message.
    /// Status messages are sent asynchronously by the robot interface to report status, errors, etc.
    /// The feature field specifies which feature the status message is from.
    /// Status message may include a data blob with additional information (feature-specific).
    struct StatusMessage
    {
        RobotFeature feature;   // Specifies which feature the status message is from
    };

    /// @brief Structure of a robot interface finished message.
    /// Finished messages are sent asynchronously by the robot interface after a long-running action has finished (successfully or with failure).
    /// The action_id field identifies the action instance that has finished. The success field indicates whether the action completed successfully or with failure.
    /// Finished message may include a data blob with additional information (feature-specific).
    struct FinishedMessage
    {
        uint64_t action_id;     // Identifies the action instance that has finished
        bool success;           // Indicates whether the action completed successfully or with failure
    };
}