#pragma once

#include "structs.h"

#include "module_helpers/robot_interface/cpp17_utils.h"

#include <cstddef>
#include <cstdint>
#include <vector>
#include <string>
#include <variant>

// Forward declaration of BufferReader so we don't pull in the helper here.
namespace aergo::module::helpers::serialization_helper::deserialization
{
    class BufferReader;
}

/// @brief Implemenation of robot control feature.
/// Start requests include move commands (move joint, move linear, move arc, move trajectory) and get robot specs request.
///    Move commands shall initiate robot movement and return immediately with SuccessInProgress response (with action_id) if movement started successfully, no response data.
///       If movement could not be started, Failure response is returned with optional error message in response data.
///    Get robot specs request returns Success response with required response data containing robot specifications.
/// Update requests include cancel movement command.
///    Cancel movement command shall stop any ongoing robot movement and return immediately with Success response.
///       If the cancel could not be performed, Failure response is returned with optional error message in response data.
/// Status messages include periodic robot status updates (current pose, joint positions, status - in extra data generated by statusMessage method).
///    Status messages shall be sent periodically to report the current state of the robot.
/// Finished messages include completion notification for long-running move commands, they indicate success/failure externally (via message_types.h) and include optional error message in extra data on failure.
///    Finished messages shall be sent after a long-running move command has completed (successfully or with failure).
namespace aergo::module::helpers::robot_interface::robot_control
{
    /// @brief Major protocol version of robot control messages.
    inline constexpr std::uint8_t ROBOT_CONTROL_MAJOR_VERSION = 1;

    namespace start
    {
        namespace requests
        {
            /// @brief Type tag for start request payloads.
            enum class RequestType : std::uint8_t
            {
                MoveJoint      = 0,
                MoveLinear     = 1,
                MoveArc        = 2,
                MoveTrajectory = 3,
                GetRobotSpecs  = 4,
            };

            constexpr uint64_t MAX_SUPPORTED_JOINTS = 16; // maximum joints supported in move joint request, throws if exceeded
            constexpr uint64_t MAX_SUPPORTED_POSES = 32768; // maximum poses supported in move trajectory request, throws if exceeded
            constexpr uint64_t MAX_ERROR_MESSAGE_LENGTH = 4096; // maximum error message length, clipped if exceeded

            namespace serialization
            {
                /// @brief Build a request to move the robot's joints to the specified target positions. Maximum supported joint count is 16.
                /// Layout (payload):
                ///    [u8 version][u8 type=MoveJoint]
                ///    [u8 joint_count][joint_count * f64 joint_targets]
                ///    [f64 speed][f64 acceleration]
                /// @param joint_targets The target joint positions to move to.
                /// @param speed The speed to move at, in rad/s.
                /// @param acceleration The acceleration to use, in rad/s^2.
                /// @return A serialized request message.
                std::vector<std::byte>& moveJoint(std::vector<std::byte>& buffer, Span<const double> joint_targets, double speed, double acceleration);

                /// @brief Build a request to move the robot from its current pose to a target pose in a linear fashion.
                /// Poses are specified in world coordinates and represent the end-effector pose.
                /// Layout (payload):
                ///    [u8 version][u8 type=MoveLinear]
                ///    [Pose:7xf64 pose_target][f64 speed][f64 acceleration]
                /// @param pose_target The target pose to move to.
                /// @param speed The speed to move at, in m/s.
                /// @param acceleration The acceleration to use, in m/s^2.
                /// @return A serialized request message.
                std::vector<std::byte>& moveLinear(std::vector<std::byte>& buffer, Pose pose_target, double speed, double acceleration);

                /// @brief Build a request to move the robot along an arc starting at the current pose, passing through a control point, and ending at a target pose.
                /// Poses are specified in world coordinates and represent the end-effector pose.
                /// Layout (payload):
                ///    [u8 version][u8 type=MoveArc]
                ///    [Pose:7xf64 pose_through][Pose:7xf64 pose_target]
                ///    [f64 speed][f64 acceleration]
                ///    [OrientationType:u8 orientation_type]
                ///    [bool as_circle][f64 circle_percentage]
                /// @param pose_through The control point for the arc.
                /// @param pose_target The target pose to move to.
                /// @param speed The speed to move at, in m/s.
                /// @param acceleration The acceleration to use, in m/s^2.
                /// @param orientation_type The type of orientation to use.
                /// @param as_circle If true, the movement will be treated as percentage of a full circle instead of an arc segment ending at the target.
                /// @param circle_percentage The percentage of the full circle to move along if as_circle is true, non-negative value, where 1.0 represents a full circle (can be greater than 1.0 for multiple revolutions).
                /// @return A serialized request message.
                std::vector<std::byte>& moveArc(std::vector<std::byte>& buffer, Pose pose_through, Pose pose_target, double speed, double acceleration, OrientationType orientation_type, bool as_circle, double circle_percentage);

                /// @brief Build a request to move the robot along a trajectory defined by a series of poses. Robot's current pose is the start of the trajectory.
                ///        Robot will move through each pose in the list sequentially, stopping at the last pose. In between poses, the robot
                ///        will fit a smooth curve to avoid decelerating to a stop at each intermediate pose.
                ///        Poses are specified in world coordinates and represent the end-effector pose.
                ///        Maximum supported pose count is 32768.
                /// Layout (payload):
                ///    [u8 version][u8 type=MoveTrajectory]
                ///    [u64 pose_count][pose_count * Pose:7xf64 pose_targets]
                ///    [f64 speed][f64 acceleration]
                ///    [OrientationType:u8 orientation_type]
                /// @param pose_targets The target poses to move through, robot will stop at the last pose in the list.
                /// @param speed The speed to move at, in m/s.
                /// @param acceleration The acceleration to use, in m/s^2.
                /// @param orientation_type The type of orientation to use.
                /// @return A serialized request message.
                std::vector<std::byte>& moveTrajectory(std::vector<std::byte>& buffer, Span<const Pose> pose_targets, double speed, double acceleration, OrientationType orientation_type);

                /// @brief Build a request to get the robot's specifications.
                /// Layout (payload):
                ///    [u8 version][u8 type=GetRobotSpecs]
                /// @return A serialized request message.
                std::vector<std::byte>& getRobotSpecs(std::vector<std::byte>& buffer);
            }


            namespace deserialization
            {
                using BufferReader = aergo::module::helpers::serialization_helper::deserialization::BufferReader;

                struct MoveJointRequest
                {
                    std::vector<double> joint_targets;    // in radians
                    double speed{};                       // in rad/s
                    double acceleration{};                // in rad/s^2
                };

                struct MoveLinearRequest
                {
                    Pose   pose_target{};                 // end effector pose in world coordinates
                    double speed{};                       // in m/s
                    double acceleration{};                // in m/s^2
                };

                struct MoveArcRequest
                {
                    Pose            pose_through{};       // control point for the arc in world coordinates
                    Pose            pose_target{};        // end effector pose in world coordinates
                    double          speed{};              // in m/s
                    double          acceleration{};       // in m/s^2
                    OrientationType orientation_type{};   // type of orientation to use
                    bool            as_circle{};          // if true, treat movement as percentage of full circle
                    double          circle_percentage{};  // percentage of full circle to move along if as_circle is true
                };

                struct MoveTrajectoryRequest
                {
                    std::vector<Pose> pose_targets;       // end effector poses in world coordinates
                    double            speed{};            // in m/s
                    double            acceleration{};     // in m/s^2
                    OrientationType   orientation_type{}; // type of orientation to use
                };

                struct GetRobotSpecsRequest
                {
                    // no payload
                };

                using RequestVariant = std::variant<
                    MoveJointRequest,
                    MoveLinearRequest,
                    MoveArcRequest,
                    MoveTrajectoryRequest,
                    GetRobotSpecsRequest
                >;

                /// @brief Deserialize a start request from the buffer.
                /// Expects the layout documented in the serialization section.
                /// @return true on success, false on version mismatch, unknown type or parse error.
                bool deserialize(BufferReader& reader, RequestVariant& out_request);
            }
        }

        namespace responses
        {
            enum class ResponseType : std::uint8_t
            {
                RobotSpecs = 0
            };

            namespace serialization
            {
                /// @brief Build a response containing the robot's specifications. Response data for GET_ROBOT_SPECS requests.
                /// Layout (payload):
                ///    [u8 version][u8 type=RobotSpecs]
                ///    [f64 max_velocity_linear][f64 max_velocity_angular]
                ///    [f64 max_acceleration_linear][f64 max_acceleration_angular]
                ///    [u8 num_joints][num_joints * {[f64 joint_min][f64 joint_max]}]
                /// @param buffer Buffer to serialize the response into.
                /// @param specs The robot specifications to include in the response.
                /// @return A serialized response message.
                std::vector<std::byte>& robotSpecs(std::vector<std::byte>& buffer, const RobotSpecs& specs);

                // Error message serialization is in common namespace
            }

            namespace deserialization
            {
                using BufferReader = aergo::module::helpers::serialization_helper::deserialization::BufferReader;

                /// @brief Deserialize robot specifications from the response buffer.
                /// Expects the layout documented in the serialization section.
                /// @return true on success, false on version mismatch, unknown type or parse error.
                bool deserializeRobotSpecs(BufferReader& reader, RobotSpecs& out_robot_specs);
            }
        }
    }

    namespace update
    {
        namespace requests
        {
            enum class MoveRequest : std::uint8_t
            {
                CancelMovement = 0,
            };

            namespace serialization
            {
                /// @brief Build an update request for a current movement.
                /// Layout (payload):
                ///    [u8 version][u8 request_type]
                /// @param buffer Buffer to serialize the request into.
                /// @return A serialized request message.
                std::vector<std::byte>& moveRequest(std::vector<std::byte>& buffer, MoveRequest request_type);
            }

            namespace deserialization
            {
                using BufferReader = aergo::module::helpers::serialization_helper::deserialization::BufferReader;

                /// @brief Deserialize an update request from the buffer.
                /// Expects the layout documented in the serialization section.
                /// @return true on success, false on version mismatch, unknown type or parse error.
                bool deserializeMoveRequest(BufferReader& reader, MoveRequest& out_move_request);
            }
        }
        
        // Success / Failure response corresponds to cancel started and does not support cancelling.
        // With failure we can get optional error message in common namespace.
        namespace responses
        {
            namespace serialization {}
            namespace deserialization {}
        }
    }
    
    // error message serialization is in common namespace
    namespace finished_messages
    {
        namespace serialization {}
        namespace deserialization {}
    }

    namespace status_messages
    {
        namespace serialization
        {
            /// @brief Build a status message indicating the robot's current status, pose, and joint positions.
            /// This message shall be sent periodically so that the current state of the robot can be monitored.
            /// Layout (payload):
            ///    [u8 version]
            ///    [u64 timestamp_us]
            ///    [Pose:7xf64 base_pose]
            ///    [Pose:7xf64 flange_pose]
            ///    [Pose:7xf64 end_effector_pose]
            ///    [u8 joint_count][joint_count * f64 joint_positions]
            ///    [RobotStatus:u8 status]
            ///    [bool has_error_msg]
            ///    if has_error_msg:
            ///       [u64 msg_len][msg_len * char8 / utf-8]
            /// @param buffer Buffer to serialize the message into.
            /// @param timestamp_us Timestamp of the status message in microseconds.
            /// @param base_pose The robot's base pose in world coordinates.
            /// @param flange_pose The robot's tool flange pose in world coordinates (tool mounting point on robot, fixed)
            /// @param end_effector_pose The robot's end-effector pose in world coordinates (actual tool position, may vary based on tool attached).
            /// @param joint_positions The robot's current joint positions.
            /// @param status The robot's current status.
            /// @param error_msg Optional error message if the robot is in an error state (only serialized if status is ERROR, can be nullptr).
            /// @return A serialized status message.
            std::vector<std::byte>& statusMessage(std::vector<std::byte>& buffer, uint64_t timestamp_us, Pose base_pose, Pose flange_pose, Pose end_effector_pose, Span<const double> joint_positions, RobotStatus status, const char* error_msg);
        }

        namespace deserialization
        {
            using BufferReader = aergo::module::helpers::serialization_helper::deserialization::BufferReader;

            struct StatusMessage
            {
                uint64_t          timestamp_us{};      // timestamp of the status message in microseconds
                Pose              base_pose{};         // base pose in world coordinates
                Pose              flange_pose{};       // tool flange pose in world coordinates (mounting point on robot, fixed)
                Pose              end_effector_pose{}; // end-effector pose in world coordinates (actual tool position, may vary based on tool attached)
                std::vector<double> joint_positions;   // joint positions in radians
                RobotStatus      status{};             // current robot status
                std::string      error_msg;            // optional error message if in error state
            };

            /// @brief Deserialize a status message from the buffer.
            /// Expects the layout documented in the serialization section.
            /// @return true on success, false on version mismatch or parse error.
            bool deserializeStatusMessage(BufferReader& reader, StatusMessage& out_status_message);
        }
    }

    namespace common
    {
        namespace serialization
        {
            /// @brief Serialize an error message for failed actions.
            /// Layout (payload):
            ///    [u8 version][u64 msg_len][msg_len * char8 / utf-8]
            /// @param buffer Buffer to serialize the message into.
            /// @param error_msg The error message to include in the message.
            /// @return A serialized message.
            std::vector<std::byte>& errorMessage(std::vector<std::byte>& buffer, const char* error_msg);
        }

        namespace deserialization
        {
            using BufferReader = aergo::module::helpers::serialization_helper::deserialization::BufferReader;

            /// @brief Deserialize a finished error message.
            /// Expects the layout documented in the serialization section.
            /// @return true on success, false on version mismatch or parse error.
            bool deserializeErrorMessage(BufferReader& reader, std::string& out_message);
        }
    }
}