#pragma once

#include "structs.h"

#include <cstddef>
#include <vector>
#include <span>

/// @brief Implemenation of robot control feature.
/// Start requests include move commands (move joint, move linear, move arc, move trajectory) and get robot specs request.
///    Move commands shall initiate robot movement and return immediately with SuccessInProgress response (with action_id) if movement started successfully, no response data.
///       If movement could not be started, Failure response is returned with optional error message in response data.
///    Get robot specs request returns Success response with required response data containing robot specifications.
/// Update requests include cancel movement command.
///    Cancel movement command shall stop any ongoing robot movement and return immediately with Success response.
///       If the cancel could not be performed, Failure response is returned with optional error message in response data.
/// Status messages include periodic robot status updates (current pose, joint positions, status - in extra data generated by statusMessage method).
///    Status messages shall be sent periodically to report the current state of the robot.
/// Finished messages include completion notification for long-running move commands, they indicate success/failure externally (via message_types.h) and include optional error message in extra data on failure.
///    Finished messages shall be sent after a long-running move command has completed (successfully or with failure).
namespace aergo::module::helpers::robot_interface::robot_control
{
    namespace start
    {
        namespace requests
        {
            namespace serialization
            {
                /// @brief Build a request to move the robot's joints to the specified target positions.
                /// @param joint_targets The target joint positions to move to.
                /// @param speed The speed to move at, in rad/s.
                /// @param acceleration The acceleration to use, in rad/s^2.
                /// @param blocking Whether to block until the movement is complete.
                /// @return A serialized request message.
                std::vector<std::byte>& moveJoint(std::vector<std::byte>& buffer, std::span<const double> joint_targets, double speed, double acceleration, bool blocking);

                /// @brief Build a request to move the robot from its current pose to a target pose in a linear fashion.
                /// Poses are specified in world coordinates and represent the end-effector pose.
                /// @param pose_target The target pose to move to.
                /// @param speed The speed to move at, in m/s.
                /// @param acceleration The acceleration to use, in m/s^2.
                /// @param blocking Whether to block until the movement is complete.
                /// @return A serialized request message.
                std::vector<std::byte>& moveLinear(std::vector<std::byte>& buffer, Pose pose_target, double speed, double acceleration, bool blocking);

                /// @brief Build a request to move the robot along an arc starting at the current pose, passing through a control point, and ending at a target pose.
                /// Poses are specified in world coordinates and represent the end-effector pose.
                /// @param pose_through The control point for the arc.
                /// @param pose_target The target pose to move to.
                /// @param speed The speed to move at, in m/s.
                /// @param acceleration The acceleration to use, in m/s^2.
                /// @param blocking Whether to block until the movement is complete.
                /// @param orientation_type The type of orientation to use.
                /// @param as_circle If true, the movement will be treated as percentage of a full circle instead of an arc segment ending at the target.
                /// @param circle_percentage The percentage of the full circle to move along if as_circle is true, non-negative value, where 1.0 represents a full circle (can be greater than 1.0 for multiple revolutions).
                /// @return A serialized request message.
                std::vector<std::byte>& moveArc(std::vector<std::byte>& buffer, Pose pose_through, Pose pose_target, double speed, double acceleration, bool blocking, OrientationType orientation_type, bool as_circle, double circle_percentage);

                /// @brief Build a request to move the robot along a trajectory defined by a series of poses. Robot's current pose is the start of the trajectory.
                ///        Robot will move through each pose in the list sequentially, stopping at the last pose. In between poses, the robot
                ///        will fit a smooth curve to avoid decelerating to a stop at each intermediate pose.
                ///        Poses are specified in world coordinates and represent the end-effector pose.
                /// @param pose_targets The target poses to move through, robot will stop at the last pose in the list.
                /// @param speed The speed to move at, in m/s.
                /// @param acceleration The acceleration to use, in m/s^2.
                /// @param blocking Whether to block until the movement is complete.
                /// @param orientation_type The type of orientation to use.
                /// @return A serialized request message.
                std::vector<std::byte>& moveTrajectory(std::vector<std::byte>& buffer, std::span<const Pose> pose_targets, double speed, double acceleration, bool blocking, OrientationType orientation_type);

                /// @brief Build a request to get the robot's specifications.
                /// @return A serialized request message.
                std::vector<std::byte>& getRobotSpecs(std::vector<std::byte>& buffer);
            }


            namespace deserialization
            {
                    
            }
        }

        namespace start_responses
        {
            namespace serialization
            {
                /// @brief Build a response containing the robot's specifications. Response data for GET_ROBOT_SPECS requests.
                /// @param buffer Buffer to serialize the response into.
                /// @param specs The robot specifications to include in the response.
                /// @return A serialized response message.
                std::vector<std::byte>& robotSpecs(std::vector<std::byte>& buffer, const RobotSpecs& specs);

                // Error message serialization is in common namespace
            }

            namespace deserialization
            {

            }
        }
    }

    namespace update
    {
        namespace requests
        {
            namespace serialization
            {
                /// @brief Build a request to cancel the current robot movement.
                /// @param buffer Buffer to serialize the request into.
                /// @return A serialized request message.
                std::vector<std::byte>& cancelMovement(std::vector<std::byte>& buffer, uint64_t action_id);
            }

            namespace deserialization
            {

            }
        }

        namespace update_responses
        {
            enum class CancelMovementResult : uint8_t { STARTED = 0, NOT_SUPPORTED = 1 };

            namespace serialization
            {
                /// @brief Build a response for cancel movement request. Indicates whether cancel was started successfully or not supported.
                /// @param buffer Buffer to serialize the response into.
                /// @param result The result of the cancel movement request.
                /// @return A serialized response message.
                std::vector<std::byte>& cancelMovementResponse(std::vector<std::byte>& buffer, CancelMovementResult result);
            }

            namespace deserialization
            {

            }
        }
    }
    
    // error message serialization is in common namespace
    namespace finished_messages
    {
        namespace serialization {}
        namespace deserialization {}
    }

    namespace status_messages
    {
        namespace serialization
        {
            /// @brief Build a status message indicating the robot's current status, pose, and joint positions.
            /// This message shall be sent periodically so that the current state of the robot can be monitored.
            /// @param buffer Buffer to serialize the message into.
            /// @param timestamp_us Timestamp of the status message in microseconds.
            /// @param current_pose The robot's current pose in world coordinates (pose of the end-effector).
            /// @param joint_positions The robot's current joint positions.
            /// @param status The robot's current status.
            /// @param error_msg Optional error message if the robot is in an error state (only serialized if status is ERROR, can be nullptr).
            /// @return A serialized status message.
            std::vector<std::byte>& statusMessage(std::vector<std::byte>& buffer, uint64_t timestamp_us, Pose current_pose, std::span<const double> joint_positions, RobotStatus status, const char* error_msg);
        }

        namespace deserialization
        {

        }
    }

    namespace common
    {
        namespace serialization
        {
            /// @brief Serialize an error message for failed actions.
            /// @param buffer Buffer to serialize the message into.
            /// @param error_msg The error message to include in the message.
            /// @return A serialized message.
            std::vector<std::byte>& errorMessage(std::vector<std::byte>& buffer, const char* error_msg);
        }

        namespace deserialization
        {

        }
    }
}